### ISSUE TITLE
Web front-end?

### ISSUE THREAD

**Issue by slor** [minter/mrvoice#1]
Hello, I read on [mrvoice.net](http://mrvoice.net/) that a re-write would be welcome. What do you think about this:
- Backend in a language-of-choice (maybe keep the perl for now or use some other choice)
- HTML5 front-end that runs in the browser.

This approach would allow mrvoice to run on multiple platforms via the browser. It avoids relying on cross-platform GUI libs (TK, etc) and IMO opens up the front-end of the app to a wider dev audience.

_How it might work_

The executable is really a launcher of a tiny local web server. It also opens the browser to a local URL that is the GUI of mrvoice. The HTML GUI would make request to the backend via HTTP using JavaScript libs to give a smooth UX.

A real-world example of this approach is iPython's [notebook feature](http://ipython.org/notebook.html).

**Comment by minter** [comment]
We ended up rewriting this in Electron.js, here several years later. Check it out at https://mxvoice.app/
